steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_REPO_NAME:$SHORT_SHA', '-t', '$_REPO_NAME:latest', '.' ]
  id: 'docker-build'

images: 
- '$_REPO_NAME:$SHORT_SHA'
- '$_REPO_NAME:latest'

timeout: 1200s

options:
 logging: CLOUD_LOGGING_ONLY
 machineType: 'E2_HIGHCPU_8'
